// Generated by gencpp from file message_pkg/Keyboard_command.msg
// DO NOT EDIT!


#ifndef MESSAGE_PKG_MESSAGE_KEYBOARD_COMMAND_H
#define MESSAGE_PKG_MESSAGE_KEYBOARD_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message_pkg
{
template <class ContainerAllocator>
struct Keyboard_command_
{
  typedef Keyboard_command_<ContainerAllocator> Type;

  Keyboard_command_()
    : value()  {
    }
  Keyboard_command_(const ContainerAllocator& _alloc)
    : value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::message_pkg::Keyboard_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_pkg::Keyboard_command_<ContainerAllocator> const> ConstPtr;

}; // struct Keyboard_command_

typedef ::message_pkg::Keyboard_command_<std::allocator<void> > Keyboard_command;

typedef boost::shared_ptr< ::message_pkg::Keyboard_command > Keyboard_commandPtr;
typedef boost::shared_ptr< ::message_pkg::Keyboard_command const> Keyboard_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_pkg::Keyboard_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_pkg::Keyboard_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message_pkg::Keyboard_command_<ContainerAllocator1> & lhs, const ::message_pkg::Keyboard_command_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message_pkg::Keyboard_command_<ContainerAllocator1> & lhs, const ::message_pkg::Keyboard_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message_pkg::Keyboard_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_pkg::Keyboard_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_pkg::Keyboard_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_pkg::Keyboard_command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_pkg::Keyboard_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_pkg::Keyboard_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_pkg::Keyboard_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64e58419496c7248b4ef25731f88b8c3";
  }

  static const char* value(const ::message_pkg::Keyboard_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64e58419496c7248ULL;
  static const uint64_t static_value2 = 0xb4ef25731f88b8c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::message_pkg::Keyboard_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_pkg/Keyboard_command";
  }

  static const char* value(const ::message_pkg::Keyboard_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_pkg::Keyboard_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string value\n"
;
  }

  static const char* value(const ::message_pkg::Keyboard_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_pkg::Keyboard_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Keyboard_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_pkg::Keyboard_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_pkg::Keyboard_command_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_PKG_MESSAGE_KEYBOARD_COMMAND_H
