// Generated by gencpp from file message_pkg/App_request.msg
// DO NOT EDIT!


#ifndef MESSAGE_PKG_MESSAGE_APP_REQUEST_H
#define MESSAGE_PKG_MESSAGE_APP_REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message_pkg
{
template <class ContainerAllocator>
struct App_request_
{
  typedef App_request_<ContainerAllocator> Type;

  App_request_()
    : mode(0)
    , action(0)
    , vel(0.0)  {
    }
  App_request_(const ContainerAllocator& _alloc)
    : mode(0)
    , action(0)
    , vel(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _action_type;
  _action_type action;

   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::message_pkg::App_request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_pkg::App_request_<ContainerAllocator> const> ConstPtr;

}; // struct App_request_

typedef ::message_pkg::App_request_<std::allocator<void> > App_request;

typedef boost::shared_ptr< ::message_pkg::App_request > App_requestPtr;
typedef boost::shared_ptr< ::message_pkg::App_request const> App_requestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_pkg::App_request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_pkg::App_request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message_pkg::App_request_<ContainerAllocator1> & lhs, const ::message_pkg::App_request_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.action == rhs.action &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message_pkg::App_request_<ContainerAllocator1> & lhs, const ::message_pkg::App_request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message_pkg::App_request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_pkg::App_request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_pkg::App_request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_pkg::App_request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_pkg::App_request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_pkg::App_request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_pkg::App_request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6fb3554f499951649fc2f38c3f0f6fa";
  }

  static const char* value(const ::message_pkg::App_request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6fb3554f4999516ULL;
  static const uint64_t static_value2 = 0x49fc2f38c3f0f6faULL;
};

template<class ContainerAllocator>
struct DataType< ::message_pkg::App_request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_pkg/App_request";
  }

  static const char* value(const ::message_pkg::App_request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_pkg::App_request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
"uint8 action\n"
"float32 vel\n"
;
  }

  static const char* value(const ::message_pkg::App_request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_pkg::App_request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.action);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct App_request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_pkg::App_request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_pkg::App_request_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_PKG_MESSAGE_APP_REQUEST_H
