// Generated by gencpp from file message_pkg/Vel_msg.msg
// DO NOT EDIT!


#ifndef MESSAGE_PKG_MESSAGE_VEL_MSG_H
#define MESSAGE_PKG_MESSAGE_VEL_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int16.h>
#include <std_msgs/Int16.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Int8.h>

namespace message_pkg
{
template <class ContainerAllocator>
struct Vel_msg_
{
  typedef Vel_msg_<ContainerAllocator> Type;

  Vel_msg_()
    : pwm_left_motor()
    , pwm_right_motor()
    , vel_left_motor()
    , vel_right_motor()
    , dir()  {
    }
  Vel_msg_(const ContainerAllocator& _alloc)
    : pwm_left_motor(_alloc)
    , pwm_right_motor(_alloc)
    , vel_left_motor(_alloc)
    , vel_right_motor(_alloc)
    , dir(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int16_<ContainerAllocator>  _pwm_left_motor_type;
  _pwm_left_motor_type pwm_left_motor;

   typedef  ::std_msgs::Int16_<ContainerAllocator>  _pwm_right_motor_type;
  _pwm_right_motor_type pwm_right_motor;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _vel_left_motor_type;
  _vel_left_motor_type vel_left_motor;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _vel_right_motor_type;
  _vel_right_motor_type vel_right_motor;

   typedef  ::std_msgs::Int8_<ContainerAllocator>  _dir_type;
  _dir_type dir;





  typedef boost::shared_ptr< ::message_pkg::Vel_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_pkg::Vel_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Vel_msg_

typedef ::message_pkg::Vel_msg_<std::allocator<void> > Vel_msg;

typedef boost::shared_ptr< ::message_pkg::Vel_msg > Vel_msgPtr;
typedef boost::shared_ptr< ::message_pkg::Vel_msg const> Vel_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_pkg::Vel_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_pkg::Vel_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message_pkg::Vel_msg_<ContainerAllocator1> & lhs, const ::message_pkg::Vel_msg_<ContainerAllocator2> & rhs)
{
  return lhs.pwm_left_motor == rhs.pwm_left_motor &&
    lhs.pwm_right_motor == rhs.pwm_right_motor &&
    lhs.vel_left_motor == rhs.vel_left_motor &&
    lhs.vel_right_motor == rhs.vel_right_motor &&
    lhs.dir == rhs.dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message_pkg::Vel_msg_<ContainerAllocator1> & lhs, const ::message_pkg::Vel_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message_pkg::Vel_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_pkg::Vel_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_pkg::Vel_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_pkg::Vel_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_pkg::Vel_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_pkg::Vel_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_pkg::Vel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ce996bea8b23d23b9968c0c69988650";
  }

  static const char* value(const ::message_pkg::Vel_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ce996bea8b23d23ULL;
  static const uint64_t static_value2 = 0xb9968c0c69988650ULL;
};

template<class ContainerAllocator>
struct DataType< ::message_pkg::Vel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_pkg/Vel_msg";
  }

  static const char* value(const ::message_pkg::Vel_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_pkg::Vel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int16 pwm_left_motor\n"
"std_msgs/Int16 pwm_right_motor\n"
"std_msgs/Float32 vel_left_motor\n"
"std_msgs/Float32 vel_right_motor\n"
"std_msgs/Int8 dir\n"
"================================================================================\n"
"MSG: std_msgs/Int16\n"
"int16 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
;
  }

  static const char* value(const ::message_pkg::Vel_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_pkg::Vel_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwm_left_motor);
      stream.next(m.pwm_right_motor);
      stream.next(m.vel_left_motor);
      stream.next(m.vel_right_motor);
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vel_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_pkg::Vel_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_pkg::Vel_msg_<ContainerAllocator>& v)
  {
    s << indent << "pwm_left_motor: ";
    s << std::endl;
    Printer< ::std_msgs::Int16_<ContainerAllocator> >::stream(s, indent + "  ", v.pwm_left_motor);
    s << indent << "pwm_right_motor: ";
    s << std::endl;
    Printer< ::std_msgs::Int16_<ContainerAllocator> >::stream(s, indent + "  ", v.pwm_right_motor);
    s << indent << "vel_left_motor: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.vel_left_motor);
    s << indent << "vel_right_motor: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.vel_right_motor);
    s << indent << "dir: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_PKG_MESSAGE_VEL_MSG_H
