#ifndef STI_PARAM_CONFIG_H
#define STI_PARAM_CONFIG_H

#define ENCODER_PULSE 11
#define MOTOR_RATIO 78

#define PWM_MAX_LEFT_MOTOR 255
#define PWM_MIN_LEFT_MOTOR -255
#define PWM_MAX_RIGHT_MOTOR 255
#define PWM_MIN_RIGHT_MOTOR -255

#define TARGET_VEL 15.0     // RPM
#endif /*AGV_CONTROLLER_PARAM_CONFIG_H*/