# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from message_pkg/Vel_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Vel_msg(genpy.Message):
  _md5sum = "8ce996bea8b23d23b9968c0c69988650"
  _type = "message_pkg/Vel_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Int16 pwm_left_motor
std_msgs/Int16 pwm_right_motor
std_msgs/Float32 vel_left_motor
std_msgs/Float32 vel_right_motor
std_msgs/Int8 dir
================================================================================
MSG: std_msgs/Int16
int16 data

================================================================================
MSG: std_msgs/Float32
float32 data
================================================================================
MSG: std_msgs/Int8
int8 data
"""
  __slots__ = ['pwm_left_motor','pwm_right_motor','vel_left_motor','vel_right_motor','dir']
  _slot_types = ['std_msgs/Int16','std_msgs/Int16','std_msgs/Float32','std_msgs/Float32','std_msgs/Int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pwm_left_motor,pwm_right_motor,vel_left_motor,vel_right_motor,dir

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Vel_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pwm_left_motor is None:
        self.pwm_left_motor = std_msgs.msg.Int16()
      if self.pwm_right_motor is None:
        self.pwm_right_motor = std_msgs.msg.Int16()
      if self.vel_left_motor is None:
        self.vel_left_motor = std_msgs.msg.Float32()
      if self.vel_right_motor is None:
        self.vel_right_motor = std_msgs.msg.Float32()
      if self.dir is None:
        self.dir = std_msgs.msg.Int8()
    else:
      self.pwm_left_motor = std_msgs.msg.Int16()
      self.pwm_right_motor = std_msgs.msg.Int16()
      self.vel_left_motor = std_msgs.msg.Float32()
      self.vel_right_motor = std_msgs.msg.Float32()
      self.dir = std_msgs.msg.Int8()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2h2fb().pack(_x.pwm_left_motor.data, _x.pwm_right_motor.data, _x.vel_left_motor.data, _x.vel_right_motor.data, _x.dir.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pwm_left_motor is None:
        self.pwm_left_motor = std_msgs.msg.Int16()
      if self.pwm_right_motor is None:
        self.pwm_right_motor = std_msgs.msg.Int16()
      if self.vel_left_motor is None:
        self.vel_left_motor = std_msgs.msg.Float32()
      if self.vel_right_motor is None:
        self.vel_right_motor = std_msgs.msg.Float32()
      if self.dir is None:
        self.dir = std_msgs.msg.Int8()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.pwm_left_motor.data, _x.pwm_right_motor.data, _x.vel_left_motor.data, _x.vel_right_motor.data, _x.dir.data,) = _get_struct_2h2fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2h2fb().pack(_x.pwm_left_motor.data, _x.pwm_right_motor.data, _x.vel_left_motor.data, _x.vel_right_motor.data, _x.dir.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pwm_left_motor is None:
        self.pwm_left_motor = std_msgs.msg.Int16()
      if self.pwm_right_motor is None:
        self.pwm_right_motor = std_msgs.msg.Int16()
      if self.vel_left_motor is None:
        self.vel_left_motor = std_msgs.msg.Float32()
      if self.vel_right_motor is None:
        self.vel_right_motor = std_msgs.msg.Float32()
      if self.dir is None:
        self.dir = std_msgs.msg.Int8()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.pwm_left_motor.data, _x.pwm_right_motor.data, _x.vel_left_motor.data, _x.vel_right_motor.data, _x.dir.data,) = _get_struct_2h2fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h2fb = None
def _get_struct_2h2fb():
    global _struct_2h2fb
    if _struct_2h2fb is None:
        _struct_2h2fb = struct.Struct("<2h2fb")
    return _struct_2h2fb
